
# https://my-app-docker.herokuapp.com/server
POST http://localhost:3001/server/tentativa-resposta/ HTTP/1.1
content-type: application/json

{
    "idUsuario": "5bbe3ec0b0792f4073dcb9fd","idExercicio":"5bc4b893f952a0139c179d51","dataInicial":"2018-10-18T12:42:06.580Z",
    "linguagem": "C", 
    "resposta": "int A = 2, B = 2;\n\n assert(A==3); // A deve ter o valor 3;\n assert(B==2); // B deve ter o valor 2;"
}

POST http://localhost:3001/server/tentativa-resposta/ HTTP/1.1
content-type: application/json

{
    "idUsuario": "5bbe3ec0b0792f4073dcb9fd","idExercicio":"5bc4b893f952a0139c179d51","dataInicial":"2018-10-18T12:42:06.580Z",
    "linguagem": "C", 
    "resposta": "int A = 2, B = 2;\n\n assert(A==3); // A deve ter o valor 3;\n assert(B==2); // B deve ter o valor 2; \n assert(strcmp(\"Fulano\", \"Fulano\")==0); //Fulano deve se chamar fulano;"
}

###
POST http://my-app-docker.herokuapp.com/server/tentativa-resposta HTTP/1.1
content-type: application/json

{
    "idUsuario": "5bbe3ec0b0792f4073dcb9fd","idExercicio":"5bc4b893f952a0139c179d51","dataInicial":"2018-10-18T12:42:06.580Z",
    "linguagem": "C",
    "resposta": "#include <stdio.h>\nint main() {\nint A = 3, B =2;\n}\n\nassert(A==6); // A deve ter o valor 3;\n assert(B==2); // B deve ter o valor 2;"
}

###
POST http://localhost:3001/server/tentativa-resposta HTTP/1.1
content-type: application/json

{
    "idUsuario": "5bbe3ec0b0792f4073dcb9fd","idExercicio":"5bc4b893f952a0139c179d51","dataInicial":"2018-10-18T12:42:06.580Z",
    "linguagem": "C",
    "resposta": "#include <stdio.h>\nint main() {\nchar nome = \"Fulano\", sobrenome = \"da Silva\", nomeCompleto = \"Fulano da Silva\";\n}\n\nassert(strcmp(nome, \"Fulano\") == 0); // nome deve ter o valor Fulano;\n assert(strcmp(sobrenome, \"da Silva\") == 0); // sobrenome deve ter o valor da Silva; \n assert(strcmp(nomeCompleto, \"Fulano da Silva\") == 0); // nomeCompleto deve ter o valor Fulano da Silva;"
}

###